---
# Run playbook with --extra-vars to provide:
# - keyname   // the desired ssh key to use
# - type      // the desired ec2 instance type
# - name      // name of the VM / AMI to be created
# looks like `--extra-vars "keyname=<KEYNAME> type=<INSTANCE_TYPE> name=<VM NAME>`

- hosts: "localhost"
  vars:
    region: "us-east-1"
    # Optionally pass this along later as well so we can upgrade whichever AMI we want.
    ami_id: "ami-04505e74c0741db8d" # Ubuntu Server 22.04 LTS (HVM), SSD Volume Type
  tasks:
    - name: Launch Instance
      amazon.aws.ec2_instance:
        name: "{{ name }}"
        key_name: "{{ keyname }}"
        instance_type: "{{ type }}"
        image_id: "{{ ami_id }}"
        wait: yes
        count: 1
        region: "{{ region }}"
      register: instance

    - name: "Print instance details"
      debug:
        var: instance['instances'][0]['instance_id']

    - name: Convert to AMI
      amazon.aws.ec2_ami:
        name: "{{ name }}-{{ time.today }}"
        instance-id: "{{ instance['instances'][0]['instance_id'] }}"

