---
# Run playbook with --extra-vars to provide:
# - sshkey   // the desired ssh key to use
# - type      // the desired ec2 instance type
# - name      // VM name
- hosts: "localhost"
  vars:
    region: "us-east-1"
    ami_id: "ami-04505e74c0741db8d" # Ubuntu Server 22.04 LTS (HVM), SSD Volume Type
  tasks:
    - name: Launch Instance
      amazon.aws.ec2_instance:
        name: "{{ name }}"
        key_name: "{{ sshkey }}"
        instance_type: "{{ type }}"
        image_id: "{{ ami_id }}"
        security_group: asf-default
        wait: yes
        count: 1
        region: "{{ region }}"
      tags:
        - "launch"
