---
# tasks file for warwalrux-workstation

- name: "Add specified repository into sources list using specified filename"
  ansible.builtin.apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: "Install Packages"
  ansible.builtin.apt:
    pkg:
      - build-essential
      - make
      - gcc
      - git
      - subversion
      - openjdk-11-jdk
      - ssh
      - vim
      - google-chrome-stable
      - htop
      - geany
      - nextcloud-desktop
      - expect

- name: "Install Slack"
  community.general.snap:
    name: "slack"
    classic: yes

- name: "Install Discord"
  community.general.snap:
    name: "discord"

# Configure ASF Work area
- name: "Configure ASF workspace"
  ansible.builtin.file:
    name: "{{ asfdir }}"
    state: directory

- name: Check out Infrastructure Repositories
  ansible.builtin.git:
    name: "git@github.com:apache/{{ repo }}.git"
    dest: "/homeo/dfoulks/Restore/asf/{{ repo }}"
  with_items:
    - "infrastructure-puppet"
    - "infrastructure-p6"
