- hosts: localhost
  vars_files:
    - "{{ varsfile }}"
  tasks:
    - name: Ensure customer space exists
      become: yes
      ansible.builtin.file:
        path: "/opt/{{ client.name }}/data"
        ensure: directory

    - name: Apply Roles
      include_role: 
        name: "{{ included_role }}"
      vars:
        customer: "{{ client }}"
      with_items: "{{ client.roles }}"
      loop_control:
        loop_var: "included_role"
