- hosts: localhost
  vars_files:
    - "{{ varsfile }}"
  tasks:
    - name: Stop Bitwarden
      become: true
      command: "/opt/{{ client.name }}/bitwarden/bitwarden.sh stop"
      tags:
        - stop
        - restart
    
    - name: Start Bitwarden
      become: true
      command: "/opt/{{ client.name }}/bitwarden/bitwarden.sh start"
      tags:
        - start
        - restart
