- hosts: localhost
  vars_files:
    - "{{ varsfile }}"
  tasks:
    - name: Tear Down Jitsi
      become: true
      docker_compose:
        project_src: "/opt/{{ client.name }}/jitsi"
        state: absent

    - name: Clean up
      become: true
      ansible.builtin.file:
        path: "/opt/{{ client.name }}/jitsi"
        state: absent
