---
- hosts: webservers
  sudo: yes
  vars:
    packages:
      - docker-compose
  tasks:
    - name: Install and configure Docker
      ansible.builtin.package:
          name: "{{ packages }}"
          state: installed
