- name: Create Client
  become: true
  become_user: root
  ansible.builtin.file:
    path: "/opt/{{ customer.name }}/nextcloud"
    state: directory

- name: Deploy Docker Compose environment file
  become: true
  become_user: root
  ansible.builtin.template:
    src: env.j2
    dest: "/opt/{{ customer.name }}/nextcloud/.env"
  notify: Start NextCloud

- name: Deploy Docker Compose file
  become: true
  become_user: root
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "/opt/{{ customer.name }}/nextcloud/docker-compose.yml"
  notify: Start NextCloud
