---
- name: Pull VoltPop Listener Service git repo
  ansible.builtin.git:
    repo: https://github.com/voltpop/vp-listen
    dest: /opt/vp-listen
  notify: vp-listen
  become: yes

- name: Set up vp-listener service
  ansible.builtin.file:
    src: /opt/vp-listen/vp-listen.service
    dest: /etc/systemd/system/vp-listen.service
    state: link
  notify: vp-listen
  become: yes
