---
# Fetch the Listener service
- name: Pull VoltPop Listener Service git repo
  ansible.builtin.git:
    repo: https://github.com/voltpop/vp-listen
    dest: "/opt/{{ customer.name }}/vp-listen"
    force: yes
  notify: vp-listen
  become: yes

# Dump the configuration from the vaultfile
- name: Configure the Listener service
  ansible.builtin.copy:
    content: "{{ customer.vars.listener_config | to_nice_yaml }}"
    dest: "/opt/{{ customer.name }}/vp-listen/listen.yml"
  notify: vp-listen
  become: yes

# Configure the systemd fiddly bits
- name: Set up vp-listener service
  ansible.builtin.file:
    src: "/opt/{{ customer.name }}/vp-listen/vp-listen.service"
    dest: /etc/systemd/system/vp-listen.service
    state: link
  notify: vp-listen
  become: yes
