- name: Tear Down NextCloud
  docker_compose:
    project_src: "/opt/{{ customer.name }}/nextcloud"
    state: absent

- name: Start NextCloud
  docker_compose:
    project_src: "/opt/{{ customer.name }}/nextcloud"
  register: output

- debug:
    var: output

- name: Re-Compose NextCloud
  docker_compose:
    project_src: "/opt/{{ customer.name }}/nextcloud"
    build: no
  register: output

- debug:
    var: output

- assert:
    that: "not output.changed "

- name: Stop NextCloud
  docker_compose:
    project_src: "/opt/{{ customer.name }}/nextcloud"
    build: no
    stopped: yes
  register: output

- debug:
    var: output

#- assert:
#    that:
#      - "not web.flask_web_1.state.running"
#      - "not db.flask_db_1.state.running"

- name: Restart NextCloud
  docker_compose:
    project_src: "/opt/{{ customer.name }}/nextcloud"
    build: no
    restarted: yes
  register: output
