- hosts: localhost
  vars_files:
    - "{{ varsfile }}"
  tasks:
    - name: Tear Down Nextcloud
      become: true
      docker_compose:
        project_src: "/opt/{{ client.name }}/nextcloud"
        state: absent

    - name: Clean up
      become: true
      ansible.builtin.file:
        path: "/opt/{{ client.name }}/nextcloud"
        state: absent
