- hosts: localhost
  vars_files:
    - "{{ varsfile }}"
  tasks:
    - name: Stop Bitwarden
      become: true
      ansible.builtin.expect:
        command: "/opt/{{ customer.name }}/bitwarden/bitwarden.sh stop"
      responses:
          database files? (y/n):
          - "y"
      tags:
        - stop
    
    - name: Start Bitwarden
      become: true
      ansible.builtin.expect:
        command: "/opt/{{ customer.name }}/bitwarden/bitwarden.sh start"
      responses:
          database files? (y/n):
          - "y"
      tags:
        - start
