- hosts: localhost
  vars_files:
    - "{{ varsfile }}"
  tasks:
    - name: Stop Jitsi
      become: true
      docker_compose:
        project_src: "/opt/{{ customer.name }}/jitsi"
        build: no
        stopped: yes
      register: output
      tags:
        - stop

    - name: Start Jitsi
      become: true
      docker_compose:
        project_src: "/opt/{{ customer.name }}/jitsi"
      register: output
      tags:
        - start

    - name: Restart Jitsi
      become: true
      docker_compose:
        project_src: "/opt/{{ customer.name }}/jitsi"
        build: no
        restarted: yes
      register: output
      tags:
        - restart

    - debug:
        var: output
      tags:
        - start
        - restart
        - stop

    - assert:
        that:
          - "not web.flask_web_1.state.running"
          - "not db.flask_db_1.state.running"
        tags:
          - stop

    - assert:
        that:
          - "web.flask_web_1.state.running"
          - "db.flask_db_1.state.running"
        tags:
          - start
