---
- hosts: "{{ targets }}"
  roles:
    - cimnine.jitsi_meet
  tasks:
    - name: Install packages
      package:
        name:
          - python3-certbot-nginx
          - python3-pexpect

    - name: set hostname
      shell:
        cmd: "hostnamectl set-hostname jitsi"

    - name: add a domain
      shell:
        cmd: "echo $(curl https://ipinfo.io/ip) $(hostname -f) $(hostname) >> /etc/hosts"

    - name: Run certbot
      expect:
        command: "/usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh"
        responses:
          \[ENTER\]:
            - dfoulks@gmail.com
