---
# tasks file for Bitwarden
#
# Ensure that the client directory exists
- name: Create Client
  become: true
  become_user: root
  ansible.builtin.file:
    path: "/opt/{{ customer.name }}/bitwarden/tmp"
    state: directory

- name: "fetch the bitwarden docker script"
  become: true
  ansible.builtin.get_url:
    url: https://go.btwrdn.co/bw-sh
    dest: "/opt/{{ customer.name }}/bitwarden/bitwarden.sh"
    mode: 0700

- name: "Run the BitWarden Set up script"
  become: true
  ansible.builtin.expect:
    command: "/opt/{{ customer.name }}/bitwarden/bitwarden.sh install"
    responses:
      bitwarden.example.com:
        - "{{ customer.vars.bitwarden.url }}"
      Let's Encrypt:
        - "n"
      vault:
        - "{{ customer.vars.bitwarden.db }}"
      installation id:
        - "{{ customer.vars.bitwarden.installation_id }}"
      installation key:
        - "{{ customer.vars.bitwarden.installation_key }}"
      SSL certificate to use:
        - "n"
      self-signed SSL certificate?:
        - "y"
  notify: Start Bitwarden
